### ISSUE TITLE
Google Ads - GCLID

### ISSUE THREAD

**Issue by bmfrey12** [sirbots/ActiveCampaign-UTM-Subscription-Source#2]
Google Ads appends GCLID as the parameter instead of UTM parameters. Is there a way to update the code so that it uses the data within the GCLID for the UTM parameters?

**Comment by sirbots** [comment]
I think it should be possible to pull in the GCLID string using this. As for decoding the actual information contained in the GCLID, [this discussion](https://stackoverflow.com/questions/365888/how-to-decode-google-gclids) might be helpful.

I think my approach would be to use a tracking template with custom parameters in AdWords and then pass those values into the AC form. You would have to modify the code to store and read these parameters (just as it currently does with UTM parameters), and create custom fields in AC to store them.

I don't have time to develop something like this now, but you're free to fork and try it or submit a PR if you come up with a solution.
